Ruchi Jha

Week 2

Section 2


Numpy

1.Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [1]:
import numpy as np

A = np.arange(1, 10).reshape(3, 3)
B = np.arange(7, 16).reshape(3, 3)

print("Array A:\n", A)
print("\nArray B:\n", B)


Array A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array B:
 [[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [2]:
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))
print("Vertical Stack:\n", vertical_stack)
print("\nHorizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

Horizontal Stack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]
 [ 7  8  9 13 14 15]]


Find common elements between A and B. [Hint: Intersection of two sets]

In [3]:
common_elements = np.intersect1d(A, B)

print("Array A:", A)
print("Array B:", B)
print("Common Elements:", common_elements)

Array A: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array B: [[ 7  8  9]
 [10 11 12]
 [13 14 15]]
Common Elements: [7 8 9]


3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [4]:
mask = (A > 5) & (A < 10)

result = A[mask]

print("Original Array:", A)
print("Numbers between 5 and 10:", result)

Original Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Numbers between 5 and 10: [6 7 8 9]


4.Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [5]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

mask = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)

filtered_iris = iris_2d[mask]

print("Shape of original iris_2d:", iris_2d.shape)
print("Shape of filtered_iris:", filtered_iris.shape)
print("\nFiltered Rows:\n", filtered_iris)

Shape of original iris_2d: (150, 4)
Shape of filtered_iris: (6, 4)

Filtered Rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Pandas

1.From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [6]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

result_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

print(result_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2.Replace missing values in Min.Price and Max.Price columns with their respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()

df['Min.Price'].fillna(min_price_mean, inplace=True)
df['Max.Price'].fillna(max_price_mean, inplace=True)

print("Missing values in Min.Price after filling:", df['Min.Price'].isnull().sum())
print("Missing values in Max.Price after filling:", df['Max.Price'].isnull().sum())

Missing values in Min.Price after filling: 0
Missing values in Max.Price after filling: 0


/tmp/ipython-input-2946284227.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(min_price_mean, inplace=True)
/tmp/ipython-input-2946284227.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', tr

3.How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [8]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

row_sums = df.sum(axis=1)

filtered_df = df[row_sums > 100]

print("Original DataFrame sample:\n", df.head())
print("\nRows with sum > 100:\n", filtered_df)

Original DataFrame sample:
     0   1   2   3
0  29  38  35  39
1  33  11  21  16
2  29  31  26  23
3  35  17  15  37
4  13  28  18  20

Rows with sum > 100:
      0   1   2   3
0   29  38  35  39
2   29  31  26  23
3   35  17  15  37
6   38  29  17  30
9   30  17  27  32
10  35  22  35  26
11  31  36  13  28
14  29  25  19  37
